### ISSUE TITLE
Needs explicit type in metadata for Optional[type] fields

### ISSUE THREAD

**Issue by cdleonard** [mivade/argparse_dataclass#27]
The following class fails to parse:

```
@dataclass
class IndexOptsMinimal:
    index: Optional[int] = None
```

The following workaround is required:

```
@dataclass
class IndexOptsWorkaround:
    index: Optional[int] = field(metadata=dict(type=int), default=None)
```

Using optional arguments that are allowed to be None is such a common pattern that it deserves to supported implicitly.

**Comment by mivade** [comment]
Closed via #28.
