### ISSUE TITLE
Support positional arguments

### ISSUE THREAD

**Issue by jimbo1qaz** [mivade/argparse_dataclass#3]
Since I am in the *happy* position of building a school project and not being able to depend on click for command-line arguments, I decided to see if it was possible to combine dataclasses and argparse. Apparently your library (which I would have to rewrite anyway) doesn't make it possible to provide positional arguments. Would that be possible through another metadata flag?

**Comment by mivade** [comment]
It would be. Probably the best way to achieve this would be to indicate it should be positional via a `positional=True` flag to the `field` `metadata` dict. I don't use positional arguments too often, but that's a great idea for an additional feature.

**Comment by mivade** [comment]
Closed by #6.
