### ISSUE TITLE
Do you want to publish it in Pypi ?

### ISSUE THREAD

**Issue by TheSmike** [mivade/argparse_dataclass#36]
I don't know if this is the right place to write, but I don't know where else write it, anyway....
Are you intending to publish the lib again on pypi? I found this library very useful and it could be worth!

Thanks in advance

**Comment by mivade** [comment]
There is currently a version on PyPI but it's pretty out of date: https://pypi.org/project/argparse-dataclass/. I am not spending too much time on this project these days but I will try to get it updated there later this week (and hopefully also automate the process going forward).

**Comment by TheSmike** [comment]
Thank you. Yes, I see the version on pypi but it doesn't contain the support for the parse_known_args function, so i wrote it to you. Good job for the lib in anycase!

**Comment by mivade** [comment]
Apologies for the delay. I hope to get to this soon. For now I'm closing in favor of #29.
