### ISSUE TITLE
Field metadata being passed on to parser needs documentation

### ISSUE THREAD

**Issue by sfaroy** [mivade/argparse_dataclass#45]
If I create a dataclass like this:
```python
@dataclass
class Options:
    option1:int = 3
    """This is option1. it should be between 1 and 4"""
    option2:str = ""
    """This is option2. it should contain a name"""
```

Will the docstrings appear in the help of the argparse?

**Comment by sfaroy** [comment]
VS-code supports this format of docstring, it is very convenient as you get the documentation when you are hovering over the field (like other docstrings).

I thought it is the standard way in PEP (actually documented here: https://peps.python.org/pep-0224/)

**Comment by mivade** [comment]
> I thought it is the standard way in PEP (actually documented here: https://peps.python.org/pep-0224/)

That's listed as rejected.
